### PR TITLE
Feature/DOM-Display

### PR DESCRIPTION
**Pull request by baileydunning**
## What's this PR do?
- Reorganize scripts to be more readable
- Added method to userRepo to calculate all users ounces
- Made sure all data was accurately being displayed on the DOM #33 

## Where should the reviewer start?
- `scripts.js` 

## How should this be manually tested?
- `npm start` then click through the cards, maybe refresh the page a couple times

## Any background context you want to provide?
- We need to write a test for `calculateAllOunces` in `userRepo`
- Objects still need to be parsed properly for trending step/stair days

## Screenshots/GIFs
Screen Shot 2020-10-30 at 5 38 19 PM

## Questions:
- How are you doing today?

### CODE REVIEW

**Review by alyssajoyner — APPROVED** [review]
Bailey - I'm doing great, especially after seeing this AMAZING PR. Nice job getting all the functionality back up and running and avoiding the landmines. We will need to connect the form inputs to scripts which I think is a great next step!

**Review by kncaputo — APPROVED** [review]
Does this mean we do not need to add a method to HydrationRepository for calculate ounces? @baileydunning

**Comment by baileydunning** [comment]
@kncaputo We'll have to look into whether or not we need to keep `addDailyOunces` because it uses a `querySelectorAll` on the DOM.

**Comment by kncaputo** [comment]
Hmmmm. Okay.

**Pull request merged**
